# Generated by Django 4.1 on 2022-08-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='dava_tarihi',
            field=models.DateTimeField(blank=True, max_length=30, null=True),
        ),
    ]
