# Generated by Django 4.1 on 2022-08-14 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0008_alter_file_dava_tarihi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="lawyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="files.lawyer",
            ),
        ),
    ]
