# Generated by Django 4.1 on 2022-08-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_file_basvuru_konusu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='dosya_durumu',
            field=models.CharField(choices=[('evrak_bekleyen', 'Evrak Bekleyen'), ('talep', 'Talep'), ('dava_acilacak', 'Dava Açılacak'), ('derdest', 'Derdest'), ('ara_karar', 'Ara Karar'), ('bilir_kisi_raporu', 'Bilir Kişi Raporu'), ('karar', 'Karar'), ('icra', 'İcra'), ('odemesi_gelen', 'Ödemesi Gelen'), ('makbuz_kesilen', 'Makbuz Kesilen'), ('kapali', 'Kapalı'), ('ikinci_talep', '2. Talep')], default='', max_length=100),
        ),
    ]
