# Generated by Django 4.1 on 2022-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_file_dosya_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='kaza_tarihi',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
