# Generated by Django 4.1 on 2022-08-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_file_kaza_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='olusturan',
        ),
    ]
