# Generated by Django 4.1 on 2022-08-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_remove_file_basvurulan_file_davalı'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='davalı',
            new_name='davali',
        ),
    ]
