# Generated by Django 4.1 on 2022-08-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_rename_davalı_file_davali'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='dosya_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='kaza_tarihi',
            field=models.DateField(max_length=30),
        ),
    ]
