# Generated by Django 4.1 on 2022-08-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_alter_file_dosya_no_alter_file_kaza_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='dosya_no',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
