# Generated by Django 4.1 on 2022-08-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0021_file_dosya_notu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='basvuru_konusu',
            field=models.CharField(choices=[('hasar', 'Hasar'), ('hasar_imms', 'Hasar Imms'), ('deger_kaybi', 'Değer Kaybı'), ('deger_kaybi_imms', 'Değer Kaybı Imms'), ('hasar_ve_deger_kaybi', 'Hasar ve Değer Kaybı'), ('maluliyet', 'Maluliyet'), ('destekten_yoksun_kalma', 'Destekten Yoksun Kalma'), ('diger', 'Diğer')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='dosya_notu',
            field=models.TextField(blank=True, default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
