# Generated by Django 4.1 on 2022-08-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_alter_file_basvuru_konusu_alter_file_dosya_notu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(max_length=250, upload_to='class'),
        ),
    ]
