# Generated by Django 4.1 on 2022-08-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0025_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(max_length=260, upload_to='class'),
        ),
        migrations.CreateModel(
            name='Masraflar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eksper_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dava_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bk_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('islah_harci', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('karsi_vekalet_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('karsi_vekalet_date', models.DateField(blank=True, max_length=30, null=True)),
                ('davalidan_gelen_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('davalidan_gelen_date', models.DateField(blank=True, max_length=30, null=True)),
                ('icradan_gelen_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('icradan_gelen_date', models.DateField(blank=True, max_length=30, null=True)),
                ('muvekkile_gonderilen_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('muvekkile_gonderilen_date', models.DateField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.file')),
            ],
        ),
    ]
