# Generated by Django 4.1 on 2022-08-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0036_remove_file_dosya_notu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='class'),
        ),
    ]
