# Generated by Django 4.1 on 2022-08-30 20:31

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0039_file_dosya_notu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='dosya_notu',
            field=django_quill.fields.QuillField(),
        ),
    ]
