# Generated by Django 4.1 on 2022-08-30 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0041_alter_file_dosya_notu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='dosya_notu',
        ),
    ]
