# Generated by Django 4.1 on 2022-08-31 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0043_file_dosya_notu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='dosya_notu',
        ),
        migrations.CreateModel(
            name='File_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', django_quill.fields.QuillField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
