# Generated by Django 4.1 on 2022-08-31 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0044_remove_file_dosya_notu_file_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_notes',
            name='user',
        ),
        migrations.AddField(
            model_name='file_notes',
            name='file',
            field=models.OneToOneField( on_delete=django.db.models.deletion.CASCADE, to='files.file'),
            preserve_default=False,
        ),
    ]
