# Generated by Django 4.1 on 2022-08-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0045_remove_file_notes_user_file_notes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='masraflar',
            name='bk_gelen_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='masraflar',
            name='bk_gelen_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
