# Generated by Django 4.1 on 2022-08-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0046_masraflar_bk_gelen_date_masraflar_bk_gelen_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='dosya_no',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
