# Generated by Django 4.1 on 2022-09-14 22:34

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0047_alter_file_dosya_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_notes',
            name='note',
            field=django_quill.fields.QuillField(),
        ),
    ]
