SOURCE_CHOICES = (
        # database name and display value respectively
        ('evrak_bekleyen', 'Evrak Bekleyen'),
        ('talep', 'Talep'),
        ('dava_acilacak', 'Dava Açılacak'),
        ('derdest', 'Derdest'),
        ('ara_karar', 'Ara Karar'),
        ('bilir_kisi_raporu', 'Bilir Kişi Raporu'),
        ('karar', 'Karar'),
        ('icra', 'İcra'),
        ('odemesi_gelen', 'Ödemesi Gelen'),
        ('makbuz_kesilen', 'Makbuz Kesilen'),
        ('kapali', 'Kapalı'),
        ('ikinci_talep', '2. Talep'),
    )
BASVURU_CHOICES = (
        ('hasar', 'Hasar'),
        ('hasar_imms', 'Hasar Imms'),
        ('deger_kaybi', 'Değer Kaybı'),
        ('deger_kaybi_imms', 'Değer Kaybı Imms'),
        ('hasar_ve_deger_kaybi', 'Hasar ve Değer Kaybı'),
        ('maluliyet', 'Maluliyet'),
        ('destekten_yoksun_kalma', 'Destekten Yoksun Kalma'),
        ('odeme_bekleyen', 'Ödeme Bekleyen'),
        ('diger', 'Diğer'),

    )
DAVALI_CHOICES = (
( '0001', 'EUREKO SİGORTA A.Ş.'),
( '0002' ,  'AKSİGORTA A.Ş.'),
( '0003' ,  'GULF SİGORTA A.Ş.'),
( '0004' ,  'ANADOLU ANONİM TÜRK SİGORTA ŞİRKETİ'),
( '0005' ,  'ANKARA ANONİM TÜRK SİGORTA ŞİRKETİ'),
( '0006' ,  'GROUPAMA SİGORTA A.Ş.'),
( '0007' ,  'UNICO Sigorta AŞ.'),
( '0008' ,  'ZURICH SİGORTA A.Ş.'),
( '0009' ,  'CORPUS SİGORTA A.Ş.'),
( '0010' ,  'GENERALİ SİGORTA A.Ş.'),
( '0011' ,  'YAPI KREDİ SİGORTA A.Ş.'),
( '0012' ,  'HÜR SİGORTA A.Ş.'),
( '0013' ,  'ERGO SİGORTA A.Ş.'),
( '0014' ,  'AXA SİGORTA A.Ş.'),
( '0015' ,  'RAY SİGORTA A.Ş.'),
( '0016' ,  'ALLIANZ SİGORTA A.Ş.'),
( '0017' ,  'LIBERTY SİGORTA A.Ş.'),
( '0018' ,  'MAGDEBURGER SİGORTA A.Ş'),
( '0019' ,  'ŞEKER SİGORTA A.Ş.'),
( '0020' ,  'MAPFRE SİGORTA A.Ş.'),
( '0021' ,  'TÜRK NİPPON SİGORTA A.Ş.'),
( '0022' ,  'HDI SİGORTA A.Ş.'),
( '0023' ,  'EGE SİGORTA A.Ş.'),
( '0024' ,  'BEREKET SİGORTA A.Ş.'),
( '0025' ,  'SOMPO SİGORTA AŞ.'),
( '0026' ,  'Dubai Starr Sigorta A.Ş'),
( '0027' ,  'ANADOLU HAYAT EMEKLİLİK A.Ş.'),
( '0028' ,  'DEMİR HAYAT SİGORTA A.Ş.'),
( '0029' ,  'AGESA HAYAT VE EMEKLİLİK'),
( '0030' ,  'ALLIANZ YAŞAM VE EMEKLİLİK AŞ.'),
( '0031' ,  'METLİFE EMEKLİLİK VE HAYAT A.Ş'),
( '0032' ,  'CİV HAYAT SİGORTA A.Ş.'),
( '0033' ,  'ERGO EMEKLİLİK VE HAYAT A.Ş.'),
( '0034' ,  'GARANTİ EMEKLİLİK VE HAYAT A.Ş.'),
( '0035' ,  'MAPFRE YAŞAM SİGORTA A.Ş.'),
( '0036' ,  'ACIBADEM SAĞLIK VE HAYAT SİGORTA A.Ş.'),
( '0037' ,  'ALLIANZ HAYAT VE EMEKLİLİK A.Ş.'),
( '0038' ,  'AXA HAYAT VE EMEKLİLİK A.Ş.'),
( '0039' ,  'GROUPAMA HAYAT A.Ş.'),
( '0040' ,  'BNP PARIBAS CARDIF HAYAT SİGORTA A.Ş.'),
( '0041' ,  'CIGNA FİNANS EMEKLİLİK VE HAYAT AŞ'),
( '0042' ,  'NEOVA KATILIM SİGORTA A.Ş.'),
( '0043' ,  'CHUBB EUROPEAN GROUP LİMİTED'),
( '0044' ,  'COFACE SİGORTA'),
( '0045' ,  'BNP PARIBAS CARDIF SİGORTA'),
( '0046' ,  'KORU SİGORTA A.Ş.'),
( '0047' ,  'AEGON SİGORTA AŞ'),
( '0048' ,  'ING EMEKLİLİK VE HAYAT AŞ.'),
( '0049' ,  'TURİNS SİGORTA'),
( '0050' ,  'FİBA EMEKLİLİK AŞ.'),
( '0051' ,  'DOĞA SİGORTA A.Ş'),
( '0052' ,  'ORİENT SİGORTA A.Ş.'),
( '0053' ,  'S.S. ATLAS SİGORTA KOOPERATİFİ'),
( '0054' ,  'ETHİCA SİGORTA A.Ş.'),
( '0055' ,  'QUICK SİGORTA A.Ş.'),
( '0056' ,  'BEREKET KATILIM SİGORTA AŞ.'),
( '0057' ,  'ANA SİGORTA ANONİM ŞİRKETİ'),
( '0058' ,  'TÜRKİYE SİGORTA A.Ş.'),
( '0059' ,  'TÜRKİYE HAYAT VE EMEKLİLİK ANONİM ŞİRKETİ'),
( '0060' ,  'GRİ SİGORTA A.Ş'),
( '0061' ,  'AREX SİGORTA A.Ş.'),
( '0062' ,  'BEREKET EMEKLİLİK VE HAYAT AŞ.'),
( '0063' ,  'NN HAYAT VE EMEKLİLİK'),
( '0064' ,  'GÜVENCE HESABI'),
( '0065' ,  'Doğal Afet Sigortaları Kurumu'),
( '0066' ,  'TÜRKİYE MOTORLU TAŞIT BÜROSU'),
( '0067' ,  'BNP PARIBAS CARDIF EMEKLİLİK'),
( '0068' ,  'TARIM SİGORTALARI HAVUZ İŞLETMESİ ANONİM ŞİRKETİ'),
( '0069' ,  'Diger'),

)